name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: "mongodb+srv://jgmaxen:Oprah1313@cluster0.mdgzw.mongodb.net/cleanDb?retryWrites=true&w=majority" # Add your MongoDB URI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the server
        run: |
          cd server
          npm run build
          cd ..

      - name: Start the application
        run: npm start & # Runs in the background

      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to start..."
          sleep 15
          curl -I http://localhost:3001 || exit 1

      - name: Run Cypress tests
        run: npx cypress run
