name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start the application
        run: npm start & # Runs in the background

      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to start..."
          sleep 15 # Increase if needed
          curl -I http://localhost:3001 || exit 1

      - name: Run Cypress tests
        run: npx cypress run
